export const postHeader = [
  { key: "id", label: "ID" },
  { key: "title", label: "Title" },
  { key: "resourceUid", label: "Resource ID" },
  { key: "dateTime", label: "Date/Time" },
  { key: "content", label: "Content" },
];

export interface PostDataDto {
  id: string;
  title: string;
  resourceUid: string; // Company.id
  dateTime: string; // e.g., "2024-12"
  content: string;
}

export const PostData: PostDataDto[] = [
  {
    id: "p001",
    title: "2024 Q4 Carbon Footprint Audit Summary",
    resourceUid: "Aurora Aerospace Corp",
    dateTime: "2024-12",
    content:
      "Finalized report on Scope 1 and 2 emissions reduction progress. Exceeded the yearly reduction target by 5% through efficient manufacturing processes.",
  },
  {
    id: "p002",
    title: "Supply Chain Emissions (Scope 3) Tracking Implementation",
    resourceUid: "Deep Earth Mining",
    dateTime: "2024-11",
    content:
      "Successful integration of the new platform for real-time tracking of Scope 3 emissions generated by third-party logistics and raw material vendors.",
  },
  {
    id: "p003",
    title: "Renewable Energy Transition Feasibility Study",
    resourceUid: "BioVita Pharmaceuticals",
    dateTime: "2024-10",
    content:
      "Analysis of solar and wind power options for transitioning the main headquarters and manufacturing plants to 100% renewable energy by 2030.",
  },
  {
    id: "p004",
    title: "Waste Management Optimization Project Kickoff",
    resourceUid: "Terra Urban Systems",
    dateTime: "2024-09",
    content:
      "Launch of the project aimed at reducing non-recyclable waste volume by 30% across all operational sites by the end of Q2 2025.",
  },
  {
    id: "p005",
    title: "Quarterly Methane Leak Detection Report",
    resourceUid: "Aether Renewables",
    dateTime: "2024-08",
    content:
      "Detailed findings from the latest aerial drone surveys conducted to detect and repair fugitive methane leaks at all operational extraction sites.",
  },
  {
    id: "p006",
    title: "Employee Commuting Emissions Reduction Program",
    resourceUid: "Harvest Fresh Foods",
    dateTime: "2024-07",
    content:
      "Proposal for expanding remote work policies and launching a public transport incentive scheme to significantly cut indirect emissions.",
  },
  {
    id: "p007",
    title: "Global Regulatory Compliance Update: EU ETS Review",
    resourceUid: "Ironclad Manufacturing",
    dateTime: "2024-06",
    content:
      "Comprehensive review of the latest changes to the European Union Emissions Trading System (ETS) and its direct impact on our European operations.",
  },
  {
    id: "p008",
    title: "Data Center Energy Efficiency Metrics (PUE)",
    resourceUid: "Synergy Global Logistics",
    dateTime: "2024-05",
    content:
      "Report detailing Power Usage Effectiveness (PUE) metrics and the plan for server virtualization to decrease cooling requirements and energy consumption.",
  },
  {
    id: "p009",
    title: "Product X Lifecycle Assessment (LCA) Phase I",
    resourceUid: "Evergreen Financial Group",
    dateTime: "2024-04",
    content:
      "Initial assessment of the cradle-to-gate emissions for Product X, highlighting high-impact raw material sources for future replacement.",
  },
  {
    id: "p010",
    title: "Strategic Investment in Carbon Capture Technology",
    resourceUid: "Quantum Data Solutions",
    dateTime: "2024-03",
    content:
      "Memo detailing a $5M investment into an innovative startup specializing in scalable direct air carbon capture (DACC) solutions.",
  },
  {
    id: "p011",
    title: "Industrial Wastewater Emissions Analysis Q1",
    resourceUid: "Terra Urban Systems",
    dateTime: "2024-02",
    content:
      "Review of industrial water consumption and contaminants in discharged wastewater against mandated environmental standards for Q1 2024.",
  },
  {
    id: "p012",
    title: "2024 H1 Sustainability Goals Progress Report",
    resourceUid: "Deep Earth Mining",
    dateTime: "2024-01",
    content:
      "Mid-year review covering progress toward greenhouse gas (GHG) reduction and alignment with established sustainable development goals (SDGs) in mining operations.",
  },
  {
    id: "p013",
    title: "Fleet Electrification Pilot Program Results",
    resourceUid: "Aurora Aerospace Corp",
    dateTime: "2023-12",
    content:
      "Results from the successful six-month pilot program transitioning 30% of the service fleet to electric vehicles, detailing cost and emissions savings.",
  },
  {
    id: "p014",
    title: "Investor Dialogue on Climate Risk Disclosure",
    resourceUid: "Ironclad Manufacturing",
    dateTime: "2023-11",
    content:
      "Summary of dialogue with major investors regarding the implementation of enhanced corporate disclosure on climate-related financial risks (TCFD framework).",
  },
  {
    id: "p015",
    title: "Internal Carbon Pricing Model Implementation Plan",
    resourceUid: "Harvest Fresh Foods",
    dateTime: "2023-10",
    content:
      "Detailed plan for implementing an internal shadow price of $50 per ton of CO2e to influence capital expenditure decisions on agricultural resources.",
  },
  {
    id: "p016",
    title: "Vendor Sustainability Scorecard Rollout",
    resourceUid: "Synergy Global Logistics",
    dateTime: "2023-09",
    content:
      "Finalized rollout plan for the new vendor evaluation system, which includes a mandatory score on emissions intensity and environmental policy for logistics partners.",
  },
  {
    id: "p017",
    title: "Technology Debt Abatement for Emissions Software",
    resourceUid: "Quantum Data Solutions",
    dateTime: "2023-08",
    content:
      "Project plan to modernize the legacy emissions monitoring software to improve data integrity and reporting speed for data center operations.",
  },
  {
    id: "p018",
    title: "Site Remediation Project Approval: Site Alpha",
    resourceUid: "Evergreen Financial Group",
    dateTime: "2023-07",
    content:
      "Regulatory approval received for the remediation and soil cleanup project at the decommissioned Site Alpha, addressing historical contamination liabilities.",
  },
  {
    id: "p019",
    title: "Mandatory Employee Training: Energy Conservation",
    resourceUid: "Aether Renewables",
    dateTime: "2023-06",
    content:
      "Launch of a mandatory training module for all staff focusing on workplace energy conservation, low-carbon practices, and waste separation.",
  },
  {
    id: "p020",
    title: "Environmental Management System (EMS) Audit Prep",
    resourceUid: "BioVita Pharmaceuticals",
    dateTime: "2023-05",
    content:
      "Internal preparatory audit and documentation review prior to the external assessment for ISO 14001 certification renewal.",
  },
];

export const emmisionsData = [
  { name: "Group A", value: 400 },
  { name: "Group B", value: 300 },
  { name: "Group C", value: 300 },
  { name: "Group D", value: 200 },
  { name: "Group E", value: 278 },
  { name: "Group F", value: 189 },
];

export interface emmisionsDataDto {
  name: string;
  value: number;
  // 🌟 이 라인이 Recharts와의 타입 충돌을 해결합니다.
  [key: string]: any;
}

export const lineChartData: lineChartDataDto[] = [
  {
    name: "Page A",
    uv: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Page B",
    uv: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "Page C",
    uv: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "Page D",
    uv: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "Page E",
    uv: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "Page F",
    uv: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Page G",
    uv: 3490,
    pv: 4300,
    amt: 2100,
  },
];

export interface lineChartDataDto {
  name: string;
  uv: number;
  pv: number;
  amt: number;
}

export interface CountriesDataDto {}

export const CountriesData: CountriesDataDto[] = [];

export interface CompaniesDataDto {}

export const CompaniesData: CompaniesDataDto[] = [];
